### ISSUE TITLE
Draft

### ISSUE THREAD

**Issue by navyney** [navyney/A-Po-s-Project-#1]

**Comment by navyney** [comment]
![Uploading IMG_0850.jpeg…]()

**Comment by navyney** [comment]
![IMG_0852](https://github.com/navyney/A-Po-s-Project-/assets/141761309/652959cb-bf09-4293-96ea-839226153197)
ทำปุ่ม next ที่มุมขวาล่างด้วยน้า

**Comment by navyney** [comment]
![Uploading IMG_0850.jpeg…]()

**Comment by OatPakin** [comment]
[หน้าตาของโปรแกรม.docx](https://github.com/navyney/A-Po-s-Project-/files/14167506/default.docx)

**Comment by navyney** [comment]
![IMG_0862](https://github.com/navyney/A-Po-s-Project-/assets/141761309/0fd26e6f-30e8-4048-af8d-2299c5f9fec7)
ทำปุ่ม next ที่มุมขวาล่างด้วยน้า

**Comment by navyney** [comment]
![IMG_0863](https://github.com/navyney/A-Po-s-Project-/assets/141761309/735d9cd6-53b9-405c-ba38-22a7648341e5)
ทำปุ่ม next ที่มุมขวาล่างด้วยน้า (ลองขยับตารางขึ้นไปด้านบนอีกหน่อยดู จะได้มีพื้นที่ใส่ปุ่มคับ)

**Comment by navyney** [comment]
![Uploading IMG_0864.jpeg…]()

**Comment by navyney** [comment]
![Uploading IMG_0864.jpeg…]()

**Comment by navyney** [comment]
![IMG_0864](https://github.com/navyney/A-Po-s-Project-/assets/141761309/80596cf9-f809-4ba6-a59a-ea7a483dc06f)
ทำแค่ข้อที่เป็นคำอ่านอย่างเดียวก่อนก็ได้ (แต่ถ้าลองทำข้อที่กดเล่นเสียงแล้วเลือกตอบได้ด้วยจะดีมาก)

**Comment by navyney** [comment]
![IMG_0850](https://github.com/navyney/A-Po-s-Project-/assets/141761309/7aabb753-ea62-4b1d-b44b-08ac4b550af5)
ทำปุ่ม next ที่มุมขวาล่างด้วยน้า

**Comment by navyney** [comment]
![IMG_0869](https://github.com/navyney/A-Po-s-Project-/assets/141761309/639a5ee9-5511-4d04-8d34-93c67efef182)
![IMG_0870](https://github.com/navyney/A-Po-s-Project-/assets/141761309/4591b44e-5e51-48ca-ad71-55f48ad6258a)
อยากให้ลองทำเป็นแบบที่ scroll ลงได้ดูก่อน เพราะอยากให้เนื้อหาท้อปปิคเดียวกันอยู่หน้าเดียวกันครับ (แต่ถ้าทำไม่ได้จริงๆค่อยทำเป็นแบบปุ่ม next ก็ได้)

**Comment by navyney** [comment]
![IMG_0872](https://github.com/navyney/A-Po-s-Project-/assets/141761309/f49561b6-f9ee-491e-9b85-1510d5906625)
ระบบจะเปนประมาณนี้น้า กด next ไปอีกหน้า มีปุ่มย้อนกลับ แล้วก็มี progressbar แสดงความคืบหน้าว่าของ lesson นั้นๆเรียนไปถึงไหนแล้ว

*** quiz page mai mee poom home na jaaaaaa ***
*** ข้อยกเว้น scroll ลงเอาน้า จนกว่าจะจบข้อ 4 ค่อยมีปุ่ม next วาดผิดนิดหน่อย ***

**Comment by navyney** [comment]
![IMG_0876](https://github.com/navyney/A-Po-s-Project-/assets/141761309/2725a28e-2908-4309-b721-74928e329766)
![IMG_0906](https://github.com/navyney/A-Po-s-Project-/assets/141761309/e10c99e3-cebc-4867-97e7-d538d7b4258a)

**Comment by navyney** [comment]
![IMG_0908](https://github.com/navyney/A-Po-s-Project-/assets/141761309/5ed208e4-16ec-45b8-8e0c-3ba3d244eb1e)
