### ISSUE TITLE
meeting 26/02/2024

### ISSUE THREAD

**Issue by o0Mink0o** [navyney/A-Po-s-Project-#21]

**Comment by OatPakin** [comment]
![image](https://github.com/navyney/A-Po-s-Project-/assets/141813428/10f069bf-8687-463b-a8df-d0ab6816d8b3)
1.เนเน่ เพิ่มหน้าเรียงประโยคใส่ปุ่มโฮม
2.ปริม ไปทำหน้าควิซบทที่ 3 พร้อมกับช่วยเบสทำหน้าควิซ
3.เบส ไปแก้หน้าตาของควิซบทที่ 0 แล้วแก้บัค
4.จั้ม แก้บัคบทที่ 0
5.มิ้งรอรวมไฟล์ จากจั้ม
6.โอ๊ต จัดการไฟล์รูปภาพและทำเสียงของบทที่ 0 เพิ่ม
