### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by suphaloek66** [navyney/A-Po-s-Project-#3]

**Comment by OatPakin** [comment]
![home](https://github.com/navyney/A-Po-s-Project-/assets/141813428/8cb0daaa-0527-4643-a3eb-b5cec91e1aca)

**Comment by OatPakin** [comment]
![l0](https://github.com/navyney/A-Po-s-Project-/assets/141813428/7e000ee4-e7e2-427f-8a33-88c3acd19563)
![l1](https://github.com/navyney/A-Po-s-Project-/assets/141813428/113dfd2a-a8f4-4853-bcd2-b8f1bd47f0b6)
![l2](https://github.com/navyney/A-Po-s-Project-/assets/141813428/60a19b9c-5dc8-4df0-8162-b04d88119730)
![l3](https://github.com/navyney/A-Po-s-Project-/assets/141813428/d0a358b4-c122-4fd1-a29d-7c5d494994cd)
![q0](https://git
![q1](https://github.c
![q3](https://github.com/navyney/A-Po-s-Project-/assets/141813428/c4d83581-ec7d-4b5a-8f34-296a24496a16)
om/navyney/A-Po-s-Project-/assets/141813428/13177fb5-302a-4724-aac8-57c332043f1a)
hub.com/navyney/A-Po-s-Project-/assets/141813428/5ffcb484-ed95-4315-8ecf-10870c12afac)
![q2](https://github.com/navyney/A-Po-s-Project-/assets/141813428/75835785-d704-4a0a-bfe1-553b4463abee)

**Comment by OatPakin** [comment]
![q0](https://github.com/navyney/A-Po-s-Project-/assets/141813428/68aa899b-9177-4418-b9f4-4d4d74ba4113)
![q1](https://github.com/navyney/A-Po-s-Project-/assets/141813428/52ea978c-ccaf-4fd0-b4eb-2e7989289c42)

**Comment by OatPakin** [comment]
![Picture1](https://github.com/navyney/A-Po-s-Project-/assets/141813428/0e0e6e6c-ca1f-4ba9-bfe3-0c124cbcb06f)

**Comment by OatPakin** [comment]
![q1'1](https://github.com/navyney/A-Po-s-Project-/assets/141813428/968722b5-0d74-4d86-ae84-72d3fe12e008)
![q2 1](https://github.com/navyney/A-Po-s-Project-/assets/141813428/8b5f93bf-39c2-4eb9-9f2a-f9f2e006d426)

**Comment by OatPakin** [comment]
![open](https://github.com/navyney/A-Po-s-Project-/assets/141813428/53fa9c7c-0cc9-4902-b8c4-358d9c748c39)
