### ISSUE TITLE
pinyin

### ISSUE THREAD

**Issue by navyney** [navyney/A-Po-s-Project-#9]

**Comment by OatPakin** [comment]
[pinyin.docx](https://github.com/navyney/A-Po-s-Project-/files/14204032/pinyin.docx)

**Comment by OatPakin** [comment]
https://drive.google.com/drive/folders/1Aq5JWpfOW78jnb24FCocvAD-qIew0wEt?usp=sharing
อันนี้คือเสียงพยัญชนะ

**Comment by OatPakin** [comment]
https://drive.google.com/drive/folders/1kh7vGxBBACPwwrC77bld2k0xgUCQ0EOj?usp=sharing
แก้

**Comment by OatPakin** [comment]
https://drive.google.com/drive/folders/1prXOHbtANgjAw40IMVbUCOelDUn-lCM8?usp=sharing
เสียงสระ mp3

**Comment by OatPakin** [comment]
![l](https://github.com/navyney/A-Po-s-Project-/assets/141813428/f6a191ea-6e00-4903-9f8e-17e9f569876c)
![r](https://github.com/navyney/A-Po-s-Project-/assets/141813428/feb8930d-d6eb-4aab-8ab1-8002cc848c4f)
![previous](https://github.com/navyney/A-Po-s-Project-/assets/141813428/983391e9-dd1f-4a17-8582-4d22f4ee6402)
![next](https://github.com/navyney/A-Po-s-Project-/assets/141813428/7ed88cfe-611c-4524-aa06-82467ca33ff8)
![รูปภาพ5](https://github.com/navyney/A-Po-s-Project-/assets/141813428/666b7d8c-0979-4eda-b593-bee9e6753e63)

**Comment by OatPakin** [comment]
![t0](https://github.com/navyney/A-Po-s-Project-/assets/141813428/0d546985-d97e-47c8-99fe-45cf5f4ec610)
![t1](https://github.com/navyney/A-Po-s-Project-/assets/141813428/a69260eb-b297-49f9-a9b6-42bf837cc151)
![t2](https://github.com/navyney/A-Po-s-Project-/assets/141813428/a1afb1cd-de5f-49dd-a443-f53392621d1c)
![t3](https
![t4](https://github.com/navyney/A-Po-s-Project-/assets/141813428/9c08262e-e471-478f-9671-c162ccfc99e7)
://github.com/navyney/A-Po-s-Project-/assets/141813428/adac7b3f-b152-4a8e-9ef3-e92786e0535c)

**Comment by OatPakin** [comment]
![t3](https://github.com/navyney/A-Po-s-Project-/assets/141813428/7cc857ff-e8b0-4814-83d8-92e4fa75c3c4)

**Comment by OatPakin** [comment]
@眠いです
![t5](https://github.com/navyney/A-Po-s-Project-/assets/141813428/bc728501-95d4-49b0-bf2f-21b89e6eece3)

**Comment by OatPakin** [comment]
![t0](https://github.com/navyney/A-Po-s-Project-/assets/141813428/eda00d76-d506-4335-b870-d541bd036c63)

**Comment by OatPakin** [comment]
https://drive.google.com/drive/folders/1eUIPYQsu47p8VqRcsrj423lrJ4McK9rn?usp=sharing
อันนี้เป็นไฟล์เสียงที่เหลือของบทนี้นะครับ

**Comment by suphaloek66** [comment]
https://drive.google.com/drive/u/1/folders/1PsWhZ7nHnDpHFRP04mjECT-BCJHzE1Qb
All Sound Lesson 0 .WAV
